language: erlang

otp_release:
  - 22.0
  - 21.3
  - 20.3

before_install:
    - git clone https://github.com/erlang/rebar3.git; cd rebar3; ./bootstrap; sudo mv rebar3 /usr/local/bin/; cd ..

script:
  - make compile
  - make xref
  - make ct
  - make cover
  - make dialyzer

after_success:
  - make coveralls

sudo: false
